---
title: "L4P2"
author: "David Pereira e Rebeca Miranda"
output: html_document
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(here)
library(viridis)

library(broom)
library(modelr)


knitr::opts_chunk$set(tidy = FALSE,
                      fig.width = 6,
                      fig.height = 5,
                      echo = FALSE)

```

```{r}

dados = read.csv(here::here("data/eleicoes_2018.csv"))
dados <-  na.omit(dados)
dados <- dados %>%  filter(votos > 0,qtd_doacoes > 0, qtd_doadores > 0)

```

```{r}
dados %>% 
    na.omit(.) %>% 
    ggplot(aes(x = log10(votos), y = log10(qtd_doacoes))) + 
    geom_point()

dados %>% 
    na.omit(.) %>% 
    ggplot(aes(x = log10(votos), y = log10(qtd_doadores))) + 
    geom_point()
    

cor(log(dados$qtd_doacoes), log(dados$votos))
cor(log(dados$qtd_doadores), log(dados$votos))

```




#Modelo 


```{r}
mod = lm(votos ~ total_despesa, data = dados)



tidy(mod, conf.level = .95, conf.int = TRUE)
glance(mod)


```


```{r}
dados %>% 
    ggplot(aes(x = total_despesa, y = votos)) + 
    geom_point(size = .5, color = "#404E4D", alpha = .4) +
    

    scale_x_log10(breaks = c(1e3, 1e5, 5e6), 
                  labels = c("1k", "100k", "5M"), 
                  minor_breaks = NULL) +
    scale_y_log10(breaks = c(100, 1e3, 1e4, 1e5), 
                  labels = c("100", "1k", "10k", "100k"), 
                  minor_breaks = NULL) +
    geom_smooth(method = "lm", 
                se = F,
                size = 1.2, 
                color = "lightBlue") 

```

```{r}

dados %>% 
    ggplot(aes(x = total_despesa, y = votos)) + 
    geom_point(size = .5, color = "#404E4D", alpha = .4) +
    

    scale_x_log10(breaks = c(1e3, 1e5, 5e6), 
                  labels = c("1k", "100k", "5M"), 
                  minor_breaks = NULL) +
    scale_y_log10(breaks = c(100, 1e3, 1e4, 1e5), 
                  labels = c("100", "1k", "10k", "100k"), 
                  minor_breaks = NULL) +
    geom_smooth(method = "lm", 
                se = F,
                size = 1.2, 
                color = "orange") 

```